# Generated by Django 2.0 on 2019-08-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0002_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='country',
            name='last_updated_time',
        ),
    ]
