# Generated by Django 2.0 on 2019-08-27 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0003_auto_20190827_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
