# Generated by Django 2.0 on 2019-08-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0004_auto_20190828_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_info1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country_info2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
